ALTER TABLE users ADD COLUMN IF NOT EXISTS "Avatar_Data_URL" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "Avatar_Updated_At" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "Phone_Number" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "Organization_Name" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "Residential_Address" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "Office_Address" TEXT;

ALTER TABLE deals ADD COLUMN IF NOT EXISTS "Deal_Source" VARCHAR(10);

ALTER TABLE contacts ADD COLUMN IF NOT EXISTS "Avatar_Data_URL" TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS "Org_Avatar_Data_URL" TEXT;
