-- Additional dollar fields per deal (ARR, TCV, TLV, commissions)

ALTER TABLE deals ADD COLUMN IF NOT EXISTS "ARR" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS "TCV" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS "TLV" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS "Commission" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS "Partner_Commission" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS "Distributor_Commission" DOUBLE PRECISION NOT NULL DEFAULT 0;
